#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#222222"
bspc config focused_border_color "#000000"
bspc config presel_feedback_color "#222222"

xsetroot -cursor_name left_ptr &
wmname LG3D