# remap prefix from 'C-b' to 'C-x'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

# split panes using | and -
bind '\' split-window -h
bind '-' split-window -v
unbind '"'
unbind '%'

# reload config file
bind 'r' source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# --- Plugins ---
# Set tmux-power theme color (options: gold, red, snow, coral, sky, forest, violet, moon)
set -g @tmux_power_theme 'forest'

# Override the date section (right_z) to use DD/MM/YYYY format with the calendar icon
set -g @tmux_power_right_z ' %d/%m/%Y'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Force hide window list after plugins are loaded
run-shell "tmux set-window-option -g window-status-current-format '' && tmux set-window-option -g window-status-format ''"
